---
# Namespace for External Secrets Operator
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline

---
# Service Account for External Secrets Operator with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # This will be populated by CDK/Terraform with the IAM role ARN
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-role
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management

---
# ClusterRole for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
rules:
  # Allow managing ExternalSecret CRDs
  - apiGroups: ["external-secrets.io"]
    resources:
      - externalsecrets
      - secretstores
      - clustersecretstores
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["external-secrets.io"]
    resources:
      - externalsecrets/status
      - secretstores/status
      - clustersecretstores/status
    verbs: ["get", "update", "patch"]
  # Allow managing Kubernetes Secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Allow reading ConfigMaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow reading ServiceAccounts for IRSA
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
  # Allow reading Events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# ClusterRoleBinding for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: external-secrets-operator
  apiGroup: rbac.authorization.k8s.io
