---
# ExternalSecret for Forge API database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-api-db-credentials
  namespace: forge-api
  labels:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 1h  # Refresh every hour
  secretStoreRef:
    name: forge-api-secret-store
    kind: SecretStore
  target:
    name: forge-api-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Template for database connection string
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_NAME: "{{ .database }}"
  dataFrom:
    - extract:
        key: robco-forge/rds/credentials  # AWS Secrets Manager secret name

---
# ExternalSecret for Forge API Okta SSO credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-api-okta-credentials
  namespace: forge-api
  labels:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 24h  # Refresh daily
  secretStoreRef:
    name: forge-api-secret-store
    kind: SecretStore
  target:
    name: forge-api-okta-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: robco-forge/okta/credentials  # AWS Secrets Manager secret name

---
# ExternalSecret for Lucy AI Anthropic API key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-lucy-anthropic-key
  namespace: forge-api
  labels:
    app.kubernetes.io/name: forge-lucy
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 24h  # Refresh daily
  secretStoreRef:
    name: forge-api-secret-store
    kind: SecretStore
  target:
    name: forge-lucy-anthropic-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: robco-forge/anthropic/api-key  # AWS Secrets Manager secret name

---
# ExternalSecret for Redis connection credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-api-redis-credentials
  namespace: forge-api
  labels:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 1h  # Refresh every hour
  secretStoreRef:
    name: forge-api-secret-store
    kind: SecretStore
  target:
    name: forge-api-redis-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_URL: "redis://{{ .host }}:{{ .port }}/0"
        REDIS_HOST: "{{ .host }}"
        REDIS_PORT: "{{ .port }}"
  dataFrom:
    - extract:
        key: robco-forge/redis/credentials  # AWS Secrets Manager secret name

---
# ExternalSecret for Cost Engine database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-cost-engine-db-credentials
  namespace: forge-workers
  labels:
    app.kubernetes.io/name: forge-cost-engine
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 1h  # Refresh every hour
  secretStoreRef:
    name: forge-workers-secret-store
    kind: SecretStore
  target:
    name: forge-cost-engine-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOST: "{{ .host }}"
        DB_PORT: "{{ .port }}"
        DB_NAME: "{{ .database }}"
  dataFrom:
    - extract:
        key: robco-forge/rds/credentials  # AWS Secrets Manager secret name

---
# ExternalSecret for Grafana admin credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: forge-system
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 24h  # Refresh daily
  secretStoreRef:
    name: forge-system-secret-store
    kind: SecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: robco-forge/grafana/admin  # AWS Secrets Manager secret name

---
# ExternalSecret for JWT signing key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forge-api-jwt-key
  namespace: forge-api
  labels:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: robco-forge
spec:
  refreshInterval: 24h  # Refresh daily
  secretStoreRef:
    name: forge-api-secret-store
    kind: SecretStore
  target:
    name: forge-api-jwt-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: robco-forge/jwt/signing-key  # AWS Secrets Manager secret name
