---
# ClusterSecretStore for AWS Secrets Manager
# This allows all namespaces to reference secrets from AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: robco-forge
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update based on your region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets

---
# SecretStore for forge-api namespace
# Scoped to forge-api namespace for API and Lucy secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: forge-api-secret-store
  namespace: forge-api
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: robco-forge
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update based on your region
      auth:
        jwt:
          serviceAccountRef:
            name: forge-api-sa
            namespace: forge-api

---
# SecretStore for forge-workers namespace
# Scoped to forge-workers namespace for Cost Engine secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: forge-workers-secret-store
  namespace: forge-workers
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: robco-forge
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update based on your region
      auth:
        jwt:
          serviceAccountRef:
            name: forge-cost-engine-sa
            namespace: forge-workers

---
# SecretStore for forge-system namespace
# Scoped to forge-system namespace for monitoring secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: forge-system-secret-store
  namespace: forge-system
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: robco-forge
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Update based on your region
      auth:
        jwt:
          serviceAccountRef:
            name: grafana-sa
            namespace: forge-system
